(function(c){var e=window.AmazonUIPageJS||window.P,d=e._namespace||e.attributeErrors,a=d?d("YourAccountMultiItemLayoutBuzzAssets",""):e;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,e,d){c.when("A","ready").register("more-items-placeholder",function(a){var b=function(f,b){var c=this;this.$placeholder=f.find("."+b+"-more-items-placeholder");this.$grid=f.find("."+b+"-grid");this.$items=this.$grid.find("."+b+"-grid-item");this.$overflowItemCount=this.$placeholder.find("."+
b+"-more-items-count");this.itemCount=this.$items.size();this.lastOverflowItemCount=0;this.$placeholder.remove();this.itemCount&&(this.refresh(),a.on.resize(function(){c.refresh()}))};b.prototype.refresh=function(){var a=this.getOverflowItemCount();a!==this.lastOverflowItemCount&&(this.$placeholder.remove(),0<a&&(this.$overflowItemCount.text(a+1),this.$items.eq(this.itemCount-a-1).prepend(this.$placeholder),this.$placeholder.show()),this.lastOverflowItemCount=a)};b.prototype.getOverflowItemCount=
function(){var b=this.$grid.offset().top,c=this.$grid.height();return a.reduce(this.$items.get(),function(e,d){d=a.$(d).offset().top-b;return e+(d>=c?1:0)},0)};return b});c.when("A","more-items-placeholder","ready").execute(function(a,b){a.$(".multi-item-multi-row").each(function(){new b(a.$(this),"multi-item-multi-row")});a.$(".multi-item-single-row").each(function(){new b(a.$(this),"multi-item-single-row")})})});
/* ******** */
(function(c){var e=window.AmazonUIPageJS||window.P,d=e._namespace||e.attributeErrors,a=d?d("YourAccountInterstitialItemBuzzAssets",""):e;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,e,d){c.when("A","ready").register("more-items-placeholder-primewardrobe",function(a){var b=function(f,b){var c=this;this.$placeholder=f.find("."+b+"-more-items-placeholder");this.$grid=f.find("."+b+"-grid");this.$items=this.$grid.find("."+b+"-grid-item");this.$overflowItemCount=
this.$placeholder.find("."+b+"-more-items-count");this.itemCount=this.$items.size();this.lastOverflowItemCount=0;this.$placeholder.remove();this.itemCount&&(this.refresh(),a.on.resize(function(){c.refresh()}))};b.prototype.refresh=function(){var a=this.getOverflowItemCount();a!==this.lastOverflowItemCount&&(this.$placeholder.remove(),0<a&&(this.$overflowItemCount.text(a+1),this.$items.eq(this.itemCount-a-1).prepend(this.$placeholder),this.$placeholder.show()),this.lastOverflowItemCount=a)};b.prototype.getOverflowItemCount=
function(){var b=this.$grid.offset().top,c=this.$grid.height();return a.reduce(this.$items.get(),function(e,d){d=a.$(d).offset().top-b;return e+(d>=c?1:0)},0)};return b});c.when("A","more-items-placeholder-primewardrobe","ready").execute(function(a,b){a.$(".multi-item-multi-row").each(function(){new b(a.$(this),"multi-item-multi-row")});a.$(".multi-item-single-row").each(function(){new b(a.$(this),"multi-item-single-row")})})});
/* ******** */
(function(d){var l=window.AmazonUIPageJS||window.P,h=l._namespace||l.attributeErrors,a=h?h("YourAccountOrderCareAmzlBuzzAssets",""):l;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,l,h){"use strict";d.when("A").register("amzl-form-validator",function(a){function e(c){this.$form=a.$(c);this.requiredInputNames=this.getRequiredInputNames()}e.prototype.hasRequiredValues=function(){var c=this.getFormData();return 0===a.$.grep(this.requiredInputNames,function(b){return 0===
a.trim(c[b]||"").length}).length};e.prototype.isValid=function(){return this.hasRequiredValues()};e.prototype.getRequiredInputNames=function(){return this.$form.find(".js-flag-required:visible, input[type\x3dhidden].js-flag-required").map(function(){var c=a.$(this);return c.attr("name")||c.find("input, select").attr("name")||c.siblings("input, select").attr("name")}).get()};e.prototype.getFormData=function(){var c=this.$form.serializeArray(),b={};a.each(c,function(a){b[a.name]=a.value});return b};
return e});"use strict";d.when("A","button-with-disabled-message","amzl-form-validator").register("amzl-form",function(a,e,c){var b=function(a,b){a.find(".amzl-error-message").removeClass("aok-hidden");b&&b.enable()},f=function(a,b){var c=b.isEnabled();a&&!c?b.enable():!a&&c&&b.disable()},d=function(b,k,d){b=a.$(b);var g=b.find(".amzl-submit-button.hide-if-no-js");if(b.size()&&g.size()){d&&g.val(d);var n=new e(g,k||g.find("input").data("disabled_message"));var m=new c(b);f(m.isValid(),n);b.undelegate(".validate").delegate("input, select",
"change.validate keyup.validate keydown.validate keypress.validate",function(){f(m.isValid(),n)})}},p=function(b){var c=a.$(b),e=c.find(".amzl-action-container"),g=c.find(".amzl-error-message");e.size()&&c.delegate(".amzl-action-container-handle","change",function(b){b=a.$(b.target);var f=b.val(),k=b.closest(".a-radio").data();b.is(":checked")&&(b.closest(".amzl-action-container-handle").addClass("amzl-action-container-handle--selected").siblings(".amzl-action-container-handle").removeClass("amzl-action-container-handle--selected"),
e.addClass("aok-hidden").filter(".amzl-action-container-"+f).removeClass("aok-hidden"),d(c,k.instructionstext,k.submittext),g.addClass("aok-hidden"))})},h=function(c,e){var d=c.$target.closest("form"),f=d.attr("action"),g=d.attr("method"),k=d.serialize();a.ajax(f+"?"+k,{method:g,success:function(a){a&&"success"===a.status?l.location.href=d.find("input[name\x3dsuccessUrl]").val():b(d,e)},error:function(){b(d,e)}});!e&&c.$event.preventDefault()};if(0!==a.$("#debounceWeblabOn").length||0!==a.$("#postShipDebounce").length){var q=
a.debounce(h,500,!0);a.declarative("amzl-action-form","submit",function(b){1!==b.data.processSubmit&&b.$event.preventDefault();var a=b.$target.closest("form").find(".amzl-submit-button.hide-if-no-js");a=new e(a,a.find("input").data("processing_message"));a.disable();q(b,a)})}else a.declarative("amzl-action-form","submit",h);return function(b){b=a.$(b);b.size()&&(d(b),p(b))}});d.when("A","amzl-form","ready").execute(function(a,e){e(a.$(".amzl-action-form"))});"use strict";d.when("A","a-modal","amzl-form",
"ready").register("amzl-modal",function(a,e,c){a.on("a:popover:ajaxContentLoaded:amzl-modal",function(b){c(b.popover.$container.find(".amzl-action-form"))});return function(b,c,d){var f=c.url;c.get&&(f+=-1===f.indexOf("?")?"?":"\x26",f+=a.$.param(c.get));e.create(b,{name:"amzl-modal",header:c.title,url:f,width:d||500,dataStrategy:"ajax"}).show()}});d.when("A","a-dropdown","amzl-modal","ready").execute(function(a,e,c){a.declarative("amzl-actions-dropdown","change",function(b){var a=b.$target,d=a.val();
d&&(b=b.data[d],d=b.declarativeAction&&b.declarativeAction.action_params||{},c(a.find("option:selected"),b,d.modalWidth),e.getSelect(a).setValue(""))})});d.when("A","amzl-modal","ready").execute(function(a,e){a.declarative("amzl-actions-link","click",function(a){var b=a.$target;e(b,{title:b.text(),url:b.attr("href")},a.data.modalWidth);a.$event.preventDefault()});a.declarative("amzl-access-code-link","click",function(a){var b=a.$currentTarget.find("a");e(b,{title:b.find(".amzlAction-modalTitle").text(),
url:b.attr("href")},a.data.modalWidth);a.$event.preventDefault()})});"use strict";d.when("A","ready").execute(function(a){a.on("a:button-group:amzl-reschedule-date-picker:toggle",function(e){var c=e.selectedButton.$button.closest(".simple-date-picker__date").data("epoch"),b=e.selectedButton.$button.closest(".simple-date-picker__date").data("end_epoch"),d=e.selectedButton.$button.closest(".simple-date-picker__date").data("service_offering_token");e=e.selectedButton.$button.closest(".simple-date-picker__date").data("timezone");
a.$(".amzl-reschedule-start-time-input").val(c).trigger("change");a.$(".amzl-reschedule-end-time-input").val(b).trigger("change");a.$(".amzl-reschedule-timezone-input").val(e).trigger("change");a.$(".amzl-reschedule-service-offering-token-input").val(d).trigger("change")})});"use strict";d.when("A","a-button","a-tooltip").register("button-with-disabled-message",function(a,d,c){function b(b,c){this.$button=a.$(b);this.auiButton=d(this.$button);this.disabledMessage=c;this.auiButton.isEnabled()||this.disable()}
b.prototype.disable=function(){this.auiButton.disable();c.remove(this.$button);c.create(this.$button,{content:this.disabledMessage});return this};b.prototype.enable=function(){this.auiButton.enable();c.remove(this.$button);return this};b.prototype.isEnabled=function(){return this.auiButton.isEnabled()};return b})});
/* ******** */
(function(l){var e=window.AmazonUIPageJS||window.P,m=e._namespace||e.attributeErrors,k=m?m("YourAccountShipTrackWidgetBuzzAssets",""):e;k.guardFatal?k.guardFatal(l)(k,window):k.execute(function(){l(k,window)})})(function(l,e,m){l.when("A","ready").register("logger",function(a){return{log:function(a){a="YourAccountShipTrack_"+a;e.ue&&"function"===typeof e.ue.count&&e.ue.count(a,(e.ue.count(a)||0)+1);"function"===typeof e.uex&&e.uex("ld",a,{wb:1})}}});"use strict";var k=function(a){if(a.length){a.css({visibility:"hidden",
display:"block"});var b=a.outerHeight(!1);var c=a.outerWidth(!1);var d=a.position().left;var g=a.position().top;a.css({visibility:"visible",display:"none"})}return{height:b,width:c,left:d,top:g}},n=function(a,b,c){this.$element1=a;this.$element2=b;this.spacer="undefined"===typeof c?5:c;return this};n.prototype.getElementCoordinates=function(a){if(!a.length)return!1;var b=a.offset(),c=a.outerHeight(),d=a.outerWidth();a.is(":visible")||(b=a.show().offset(),a.hide(),a=k(a),c=a.height,d=a.width);return{height:c,
width:d,left:b.left,right:b.left+d,top:b.top,bottom:b.top+c}};n.prototype.getPositions=function(a){var b=this.getElementCoordinates(a),c=a.data("future-state");if(c){var d=a.parent().offset();var g=c["margin-top"];var f=c["margin-left"];var h="undefined"!==typeof c.left?c.left+d.left:m;d="undefined"!==typeof c.top?c.top+d.top:m}h="undefined"!==typeof h?parseInt(h,10):b.left;h+="undefined"!==typeof f?parseInt(f,10):0;f="undefined"!==typeof d?parseInt(d,10):b.top;f+="undefined"!==typeof g?parseInt(g,
10):0;return[[h,h+b.width],[f,f+b.height]]};n.prototype.willOverlap=function(){if(!this.$element1.length||!this.$element2.length||this.$element1.get(0).parentNode!==this.$element2.get(0).parentNode)return!1;var a=this.getMarginDiffs();return 0!==a.left&&0!==a.right&&0!==a.top&&0!==a.bottom};n.prototype.getMarginDiffs=function(){var a={left:0,right:0,top:0,bottom:0},b=this.spacer;var c=this.getPositions(this.$element1);var d=this.getPositions(this.$element2);var g=d[0][1]-c[0][0];var f=d[0][0]-c[0][1];
var h=d[1][1]-c[1][0];c=d[1][0]-c[1][1];a.left=g>b?Math.max(b,g+b):0;a.right=f<b?Math.min(-b,f-b):0;a.top=h>b?Math.max(b,h+b):0;a.bottom=c<b?Math.min(-b,c-b):0;return a};l.when("A","ready").register("widget-shared",function(a){var b=function(){this.shortAnimationTime=400;this.longAnimationTime=1E3;this.animationEase="ease"};b.prototype.Overlaps=n;b.prototype.getHiddenElementDimensions=k;b.prototype.stAnimate=function(b,d,g,f){if(b&&b.length){g=g||this.shortAnimationTime;f=f||this.animationEase;var c=
b.data("future-state")||{},e;for(e in d)e&&(c[e]=d[e]);b.data("future-state",c);a.animate(b,d,g,f,function(){a.isAnimated(b)||b.removeData("future-state")})}};return b})});
/* ******** */
